### ISSUE TITLE
Openwrt 24.10

### ISSUE THREAD

**Issue by agevlakh** [franzflasch/i2c-gpiod-custom-openwrt#1]
Hello! Does it work on openwrt 24.10?

**Comment by franzflasch** [comment]
Hi! I did not test it on 24.10. But I guess it should work.

**Comment by agevlakh** [comment]
> Hi! I did not test it on 24.10. But I guess it should work.

Thanks. I will make a test with 24.10

**Comment by agevlakh** [comment]
@franzflasch 
Failed to build

![Image](https://github.com/user-attachments/assets/881b7f14-4a51-4ccc-b4eb-1f495a2d8268)

**Comment by agevlakh** [comment]
`make[3]: Leaving directory '/mnt/bananapi-r2-new-project/openwrt/package/libs/uclient'
time: package/libs/uclient/compile#0.20#0.13#0.37
/mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/i2c-gpiod-custom/i2c-gpiod-custom.c:52:10: fatal error: asm-generic/gpio.h: No such file or directory
   52 | #include <asm-generic/gpio.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:243: /mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/i2c-gpiod-custom/i2c-gpiod-custom.o] Error 1
make[5]: *** [/mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/linux-6.6.73/Makefile:1921: /mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/i2c-gpiod-custom] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[4]: Leaving directory '/mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/linux-6.6.73'
make[3]: *** [Makefile:44: /mnt/bananapi-r2-new-project/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_mt7623/i2c-gpiod-custom/.built] Error 2
make[3]: Leaving directory '/mnt/bananapi-r2-new-project/openwrt/package/mypackage/i2c-gpiod-custom-openwrt/i2c-gpiod-custom'
time: package/mypackage/i2c-gpiod-custom-openwrt/i2c-gpiod-custom/compile#0.95#0.43#1.51
    ERROR: package/mypackage/i2c-gpiod-custom-openwrt/i2c-gpiod-custom failed to build.
make[2]: *** [package/Makefile:179: package/mypackage/i2c-gpiod-custom-openwrt/i2c-gpiod-custom/compile] Error 1`
